/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import React, { useRef } from "react";
import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useLoader(GLTFLoader, "/models/Pizza.glb");
  return (
    <group ref={group} {...props} scale={[5, 5, 5]} dispose={null}>
      <mesh material={materials.Cheese} geometry={nodes.Cheese.geometry} />
      <mesh material={materials.Crust} geometry={nodes.Crust.geometry} />
      <mesh material={materials.Sauce} geometry={nodes.Sauce.geometry} />
    </group>
  );
}
