/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
    Plane012: THREE.Mesh;
    Plane012_1: THREE.Mesh;
    Stool_Legs: THREE.Mesh;
    Stool_Seat: THREE.Mesh;
    Stool_Footrest001: THREE.Mesh;
    Monitor_Base: THREE.Mesh;
    Mounting_Rod_Arms: THREE.Mesh;
    Mounting_Rod_Monitor_Core: THREE.Mesh;
    Mounting_Rod_Base_Core: THREE.Mesh;
    Monitor: THREE.Mesh;
    Mounting_Rod_Monitor: THREE.Mesh;
    Adjustment_Handles: THREE.Mesh;
    Screen_Cintiq: THREE.Mesh;
    Monitor_Glass_Inlay: THREE.Mesh;
    Legs: THREE.Mesh;
    Surface: THREE.Mesh;
    Legs_Feet: THREE.Mesh;
    Base: THREE.Mesh;
    Keys: THREE.Mesh;
    Keys_Function: THREE.Mesh;
    Screen_Casing: THREE.Mesh;
    Cylinder: THREE.Mesh;
    ["Bezel-Glass"]: THREE.Mesh;
    Bezel_Rubb: THREE.Mesh;
    Macbook_Screen: THREE.Mesh;
    Wacom_Pen_Holder: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder005_1: THREE.Mesh;
    Cylinder005_2: THREE.Mesh;
    Coaster: THREE.Mesh;
    Coffee_Cup: THREE.Mesh;
    Coffee: THREE.Mesh;
    Keyboard_Shell: THREE.Mesh;
    Keyboard_Keys_Grey: THREE.Mesh;
    Keyboard_Keys_White: THREE.Mesh;
  };
  materials: {
    ["Black Plastic"]: THREE.MeshStandardMaterial;
    ["Brushed Aluminum"]: THREE.MeshStandardMaterial;
    ["Black Plastic.003"]: THREE.MeshStandardMaterial;
    ["Black Plastic.004"]: THREE.MeshStandardMaterial;
    Cintiq_Screen: THREE.MeshStandardMaterial;
    ["Black Glass"]: THREE.MeshStandardMaterial;
    ["Brown Wood"]: THREE.MeshStandardMaterial;
    Screen: THREE.MeshStandardMaterial;
    ["Blue Porcelain"]: THREE.MeshStandardMaterial;
    Coffee: THREE.MeshStandardMaterial;
    ["Gray Plastic"]: THREE.MeshStandardMaterial;
    ["White Plastic"]: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/models/Room.glb") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={nodes.Plane.material} geometry={nodes.Plane.geometry} />
      <group position={[0.33, 0.03, 0.1]}>
        <mesh
          material={materials["Black Plastic"]}
          geometry={nodes.Plane012.geometry}
        />
        <mesh
          material={materials["Brushed Aluminum"]}
          geometry={nodes.Plane012_1.geometry}
        />
      </group>
      <mesh
        material={materials["Black Plastic.003"]}
        geometry={nodes.Stool_Legs.geometry}
      />
      <mesh
        material={materials["Black Plastic.003"]}
        geometry={nodes.Stool_Seat.geometry}
      />
      <mesh
        material={materials["Black Plastic.004"]}
        geometry={nodes.Stool_Footrest001.geometry}
        position={[0, -0.62, 0.48]}
      />
      <mesh
        material={materials["Black Plastic"]}
        geometry={nodes.Monitor_Base.geometry}
      />
      <mesh
        material={materials["Brushed Aluminum"]}
        geometry={nodes.Mounting_Rod_Arms.geometry}
      />
      <mesh
        material={materials["Black Plastic"]}
        geometry={nodes.Mounting_Rod_Monitor_Core.geometry}
      />
      <mesh
        material={materials["Black Plastic"]}
        geometry={nodes.Mounting_Rod_Base_Core.geometry}
      />
      <mesh
        material={materials["Brushed Aluminum"]}
        geometry={nodes.Monitor.geometry}
      />
      <mesh
        material={materials["Brushed Aluminum"]}
        geometry={nodes.Mounting_Rod_Monitor.geometry}
      />
      <mesh
        material={materials["Brushed Aluminum"]}
        geometry={nodes.Adjustment_Handles.geometry}
      />
      <mesh
        material={materials.Cintiq_Screen}
        geometry={nodes.Screen_Cintiq.geometry}
      />
      <mesh
        material={materials["Black Glass"]}
        geometry={nodes.Monitor_Glass_Inlay.geometry}
      />
      <mesh
        material={materials["Brushed Aluminum"]}
        geometry={nodes.Legs.geometry}
      />
      <mesh
        material={materials["Brown Wood"]}
        geometry={nodes.Surface.geometry}
      />
      <mesh
        material={materials["Black Plastic"]}
        geometry={nodes.Legs_Feet.geometry}
      />
      <mesh
        material={materials["Brushed Aluminum"]}
        geometry={nodes.Base.geometry}
      />
      <mesh
        material={materials["Black Plastic"]}
        geometry={nodes.Keys.geometry}
      />
      <mesh
        material={materials["Black Plastic"]}
        geometry={nodes.Keys_Function.geometry}
      />
      <mesh
        material={materials["Brushed Aluminum"]}
        geometry={nodes.Screen_Casing.geometry}
      />
      <mesh
        material={materials["Black Plastic"]}
        geometry={nodes.Cylinder.geometry}
      />
      <mesh
        material={materials["Black Glass"]}
        geometry={nodes["Bezel-Glass"].geometry}
      />
      <mesh
        material={materials["Black Plastic"]}
        geometry={nodes.Bezel_Rubb.geometry}
      />
      <mesh
        material={materials.Screen}
        geometry={nodes.Macbook_Screen.geometry}
      />
      <mesh
        material={materials["Black Plastic"]}
        geometry={nodes.Wacom_Pen_Holder.geometry}
        position={[-0.44, 0.04, -0.07]}
      >
        <group position={[0, 0.07, 0]}>
          <mesh
            material={materials["Black Plastic"]}
            geometry={nodes.Cylinder005.geometry}
          />
          <mesh
            material={materials["Brushed Aluminum"]}
            geometry={nodes.Cylinder005_1.geometry}
          />
          <mesh
            material={materials["Blue Porcelain"]}
            geometry={nodes.Cylinder005_2.geometry}
          />
        </group>
      </mesh>
      <mesh
        material={nodes.Coaster.material}
        geometry={nodes.Coaster.geometry}
      />
      <mesh
        material={materials["Blue Porcelain"]}
        geometry={nodes.Coffee_Cup.geometry}
      />
      <mesh material={materials.Coffee} geometry={nodes.Coffee.geometry} />
      <mesh
        material={nodes.Keyboard_Shell.material}
        geometry={nodes.Keyboard_Shell.geometry}
        position={[0, 0.04, 0.09]}
      >
        <mesh
          material={materials["Gray Plastic"]}
          geometry={nodes.Keyboard_Keys_Grey.geometry}
          position={[0, 0.01, 0.01]}
        />
        <mesh
          material={materials["White Plastic"]}
          geometry={nodes.Keyboard_Keys_White.geometry}
          position={[0, 0.01, 0.01]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Room.glb");
